# Generated by Django 3.2.6 on 2021-08-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
