# Generated by Django 3.2.6 on 2021-08-09 10:36

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210807_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='―――――', max_length=100, verbose_name='Адрес компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='―――――', max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='leader_name',
            field=models.CharField(help_text='―ФИО', max_length=100, verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(help_text='―――――', max_length=100, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_address',
            field=models.EmailField(help_text='―――――', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='manager_name',
            field=models.CharField(help_text='―ФИО', max_length=100, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, help_text='―пример +380XXXXXXXXX', max_length=17, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$'), django.core.validators.MinValueValidator(1)], verbose_name='Телефон'),
        ),
    ]
