# Generated by Django 3.2.6 on 2021-08-10 09:07

import ckeditor.fields
import crm.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210809_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', '-name', 'company', 'price', 'start_date', 'end_date']},
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, help_text='―пример +380XXXXXXXXX', max_length=17, validators=[django.core.validators.RegexValidator(regex='^(\\s*)?(\\+)?([- _():=+]?\\d[- _():=+]?){10,14}(\\s*)?$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='―――――', max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(verbose_name='Срок окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='―――――', max_length=100, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(validators=[crm.models.start_date_valid], verbose_name='Срок начала проекта'),
        ),
    ]
