# Generated by Django 3.2.6 on 2021-08-10 11:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210810_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(help_text='― дд.мм.гггг.', verbose_name='Дата окончания проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(help_text='―――――', verbose_name='Стоимость проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(help_text='― дд.мм.гггг.', verbose_name='Дата начала проекта'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_of_reference', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField(help_text='―――――', max_length=1000, null=True, verbose_name='Описание')),
                ('rating', models.TextField()),
                ('company', models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Название компании')),
                ('manager', models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('project', models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.project', verbose_name='Название проекта')),
            ],
        ),
    ]
