# Generated by Django 3.2.6 on 2021-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20210810_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='company',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.TextField(verbose_name='Канал обращения'),
        ),
    ]
