# Generated by Django 3.2.6 on 2021-08-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20210810_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(choices=[('Телефонный звонок', 'Телефонный звонок'), ('Письмо на E-mail', 'Письмо на E-mail'), ('Переписка в мессенджере', 'Переписка в мессенджере')], max_length=100, verbose_name='Вид связи'),
        ),
    ]
