# Generated by Django 3.2.6 on 2021-08-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210811_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(help_text='―――――', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.company', verbose_name='Название компании'),
        ),
    ]
