# Generated by Django 3.2.6 on 2021-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Менеджер'),
        ),
    ]
