# Generated by Django 3.2.6 on 2021-08-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_auto_20210815_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'permissions': (('auth_user_view', 'Can view permission'), ('user_can_create_update_delete', 'Can can create_update_delete'))},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['company'], 'permissions': (('auth_user_view', 'Can view permission'),)},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['company'], 'permissions': (('auth_user_view', 'Can view permission'),)},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['company'], 'permissions': (('auth_user_view', 'Can view permission'),)},
        ),
    ]
