# Generated by Django 3.2.6 on 2021-08-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20210815_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'permissions': (('auth_user_view', 'Can view permission'), ('user_can_create_update_delete', 'Can create_update_delete'))},
        ),
    ]
