# Generated by Django 3.2.6 on 2021-08-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title'], 'permissions': (('user_can_create_update_delete', 'Can create_update_delete'),)},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['company']},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['company']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['company']},
        ),
    ]
