# Generated by Django 3.2.6 on 2021-08-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20210815_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title']},
        ),
    ]
