# Generated by Django 3.2.6 on 2021-08-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='managercrm',
            name='name',
        ),
    ]
