# Generated by Django 3.2.6 on 2021-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_auto_20210818_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, help_text='―――――', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='managercrm',
            name='full_name',
            field=models.CharField(blank=True, help_text='―――――', max_length=100, verbose_name='ФИО'),
        ),
    ]
