# Generated by Django 3.2.6 on 2021-08-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_auto_20210818_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
