# Generated by Django 3.2.6 on 2021-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_auto_20210818_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='managercrm',
            name='first_name_manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='managercrm',
            name='last_name_manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(help_text='―――――', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='managercrm',
            name='full_name',
            field=models.CharField(help_text='―――――', max_length=100, verbose_name='ФИО'),
        ),
    ]
