# Generated by Django 3.2.6 on 2021-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_auto_20210818_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='managercrm',
            name='first_name_manager',
        ),
        migrations.RemoveField(
            model_name='managercrm',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='managercrm',
            name='last_name_manager',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='Заказчик', max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
        migrations.AlterField(
            model_name='managercrm',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
    ]
