# Generated by Django 3.2.6 on 2021-08-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_auto_20210819_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(help_text='―――――', max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='managercrm',
            name='full_name',
            field=models.CharField(help_text='―――――', max_length=100, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
        migrations.AlterField(
            model_name='managercrm',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
    ]
