# Generated by Django 3.2.6 on 2021-08-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_auto_20210819_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', '-name', 'company', 'price', 'start_date', 'end_date', 'status_pro']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Заказчик', max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
        migrations.AlterField(
            model_name='managercrm',
            name='name',
            field=models.CharField(default='Менеджер', max_length=100, null=True, verbose_name='Имя Фамилия (подтвердите)'),
        ),
    ]
